version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.28
    platform: linux/x86_64 # 추가된 라인
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: juniperbin
